language: go

go:
  - "1.10"
  - master

before_install:
  - go get -t -v ./...
  
install:
  - go get -v github.com/golang/lint/golint
  - go get -v golang.org/x/tools/cmd/cover
  - go get -v github.com/mattn/goveralls

script:
  - $HOME/gopath/bin/goveralls -service=travis-ci 
