openapi: 3.0.0
# Added by API Auto Mocking Plugin
servers:
# Added by API Auto Mocking Plugin
  - description: Matrix Cloud AppStack API
    url: "https://account.matrixcloud.io"
info:
  description: This is a simple API
  version: "1.1.0"
  title: Matrix Cloud AppStack API [非网关]
  contact:
    email: "hongwei.mei@changhong.com"
  license:
    name: Changhong SSC 2.0
    url: ""
tags:
  - name: templates
    description: "应用模版管理"
paths:
  /pets:
    get:
      summary: List all pets
      operationId: listPets
      tags:
        - pets
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          type: integer
          format: int32
      responses:
        "200":
          description: An paged array of pets
          headers:
            x-next:
              type: string
              description: A link to the next page of responses
          schema:
            $ref: '#/definitions/Pets'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
    post:
      summary: Create a pet
      operationId: createPets
      tags:
        - pets
      responses:
        "201":
          description: Null response
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
  /pets/{petId}:
    get:
      summary: Info for a specific pet
      operationId: showPetById
      tags:
        - pets
      parameters:
        - name: petId
          in: path
          required: true
          description: The id of the pet to retrieve
          type: string
      responses:
        "200":
          description: Expected response to a valid request
          schema:
            $ref: '#/definitions/Pets'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
  /users:
    post:
      summary: Create an user
      operationId: createUsers
      tags:
        - users
      requestBody:
        description: "add user"
        content:
          application/json:
            schema:
              $ref: "#/definitions/User"   
      responses:
        "201":
          description: Null response
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  User:
    type: object
    required:
      - email
      - name
      - passwd
    properties:
      email:
        type: string
      name:
        type: string
      passwd:
        type: string
  Users:
     type: array
     items:
      $ref: '#/definitions/User'    
  Pet:
    required:
      - id
      - name
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      tag:
        type: string
  Pets:
    type: array
    items:
      $ref: '#/definitions/Pet'
  Error:
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string