apiVersion: v1
kind: Deployment
metadata:
  name: quant-deploy
spec:
  replicas: 1 
  template:
    metadata:
      labels:
        app: quant
    spec:
      containers:
      - name: quant
        image: localhost:5000/quant
        ports:
        - containerPort: 8000






















