smtp_host: "smtp.163.com"
smtp_port: 25
smtp_user: "xiyanxiyan10@163.com"
smtp_pwd: "xiyanxiyan10"
admin_user: "xiyanxiyan10"
admin_pwd: "quant19890321"
smtp_interval: 180
smtp_cachesize: 20
smtp_mails: 
    - "xiyanxiyan10@163.com"
    - "873706510@qq.com"
    - "xiyanxiyan10@hotmail.com"
    - "pjbao@aliyun.com"
    - "cn998@189.cn"
    - "wslwd16357383@163.com"

